default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: ricky
  password: IAmExtr4Ord1n4ry!

development:
  <<: *default
  database: graphql_api

test:
  <<: *default
  database: graphql_api_test
